### ISSUE TITLE
末期ガン再発

### ISSUE THREAD

**Issue by sksat** [sksat/mc.yohane.su#130]
- #127 とほぼ同一
- 微妙に様子が違うのは，何？

様子:
```
Picked up JAVA_TOOL_OPTIONS: -Xms2G -Xmx2G
Downloading vanilla jar...
Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 0 in class file java/util/concurrent/atomic/Striped64$1
	at java.base/java.util.concurrent.atomic.Striped64.<clinit>(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.addCount(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.doPut(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentSkipListSet.add(Unknown Source)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at java.base/java.net.InetAddress.getByName(Unknown Source)
	at java.base/java.net.InetSocketAddress.<init>(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at io.papermc.paperclip.Paperclip.checkVanillaJar(Paperclip.java:185)
	at io.papermc.paperclip.Paperclip.checkPaperJar(Paperclip.java:116)
	at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:89)
	at io.papermc.paperclip.Paperclip.main(Paperclip.java:40)
```

**Comment by sksat** [comment]
まあとりあえず稼働率を下げないために`podman-compose`で走らせておくか...

**Comment by sksat** [comment]
そもそも`docker-compose`関連の操作がクソ遅いなどもある

**Comment by sksat** [comment]
これはkasumiが爆死してたのが悪いしkasumiは崩御したので閉じ
