### ISSUE TITLE
鶏強制労働プラグインが死んでいる

### ISSUE THREAD

**Issue by Siro256** [sksat/mc.yohane.su#164]
プラグインが正常に起動していない模様
![image](https://user-images.githubusercontent.com/26498306/142856849-cece7598-cf8d-4471-96d5-e729def276c1.png)

**Comment by sksat** [comment]
```
[08:37:16 INFO]: [ConfineChickens] Enabling ConfineChickens v1.0.0
[08:37:16 ERROR]: Error occurred while enabling ConfineChickens v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: kotlin.jvm.internal.Intrinsics
	at dev.siro256.spigotpl.confinechickens.ConfineChickens.onEnable(ConfineChickens.kt:10) ~[ConfineChickens-1.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at net.minecraft.server.MinecraftServer$$Lambda$3692/0x00000000e5dd1d88.run(Unknown Source) ~[app:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-"e22a1a9"]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 12 more
```
とのこと

**Comment by sksat** [comment]
なんも見ずにマージしたけどCIでも死んでるしおま環ではなさそう
https://github.com/sksat/mc.yohane.su/runs/4278687470?check_suite_focus=true
@Siro256

**Comment by Siro256** [comment]
Kotlinのランタイムを入れ忘れていますね...夜修正版リリースします

**Comment by Siro256** [comment]
✅ リリース
https://github.com/Siro256/ConfineChickens/releases/tag/v1.0.1

**Comment by sksat** [comment]
よっしゃ

**Comment by sksat** [comment]
- #167 

OK

**Comment by Siro256** [comment]
Spigotで検証していたので気付かなかったんですが、PaperMCのせいで正常に動作していないっぽいです  修正します

**Comment by sksat** [comment]
おや

**Comment by Siro256** [comment]
PaperMCのバグを踏んでいそう

**Comment by sksat** [comment]
そんにゃ〜〜〜

**Comment by Siro256** [comment]
https://github.com/PaperMC/Paper/issues/6928

**Comment by Siro256** [comment]
どうやら設定がある様子  https://paper.readthedocs.io/en/latest/server/configuration.html#allow-non-player-entities-on-scoreboards

**Comment by sksat** [comment]
ほほん

**Comment by sksat** [comment]
とりあえずcurrent statusを突っ込んだのでご自由に
https://github.com/sksat/mc.yohane.su/commit/e1ba795e6e5f37f2107c356be15c5c8d43b1c1a3
